# Generated by Django 5.0.4 on 2024-05-20 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='content',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='upldfile'),
        ),
        migrations.AlterField(
            model_name='content',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='upldfile'),
        ),
        migrations.AlterField(
            model_name='content',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='upldfile'),
        ),
        migrations.AlterField(
            model_name='content',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childrens', to='myapp.content'),
        ),
        migrations.AlterModelTable(
            name='content',
            table='content',
        ),
    ]
