# Generated by Django 5.0.4 on 2024-05-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_actions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'terminal_status',
            },
        ),
    ]
